version: "2.2"

services: 
  ldap-service:
    image: odk/openldap
    env_file:
      - ldap.env
  db:
    image: postgres:9.6
    env_file:
      - db.env
  db-bootstrap:
    image: odk/db-bootstrap
    depends_on:
      - db
    env_file:
      - db.env
      - sync.env
  sync:
    image: odk/sync-endpoint
    depends_on:
      - db-bootstrap
      - ldap-service
    env_file:
      - sync.env
    volumes:
      - ./security.properties:/run/secrets/org.opendatakit.aggregate.security.properties:ro
      - ./jdbc.properties:/run/secrets/org.opendatakit.aggregate.jdbc.properties:ro