version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u171-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - setup_remote_docker
      - run: mvn validate
      - run: mvn -pl sync-endpoint-war/ clean install
      - run: mvn -pl odk-rest-interface/ clean install
      - run: mvn -nsu -e -pl sync-endpoint-docker-test/ compile
      - run: mvn -o -pl postgres-test/ compile
      - run: mvn -o -pl mysql-test/ compile
      - run: mvn test
      - run: mvn package
      - run: mvn varify
      - run: mvn install
      - run: cd..
      - run: docker build --pull -t odk/sync-web-ui https://github.com/opendatakit/sync-endpoint-web-ui.git
      - run: docker build --pull -t odk/db-bootstrap db-bootstrap
      - run: docker build --pull -t odk/openldap openldap
      - run: docker build --pull -t odk/phpldapadmin phpldapadmin
      - run: docker stack deploy -c docker-compose.yml syncldap
